fix: remove extra spaces in DaemonSet tolerations definition
This fix is required for a successful deployment of DaemonSet

Otherwise we get an error
```
error: error parsing https://raw.githubusercontent.com/clustership/inspektor-gadget/master/openshift/deployment.yaml
error converting YAML to JSON: yaml: line 22: mapping values are not allowed in this context
```